=== BulkSecurityGeneratorProjectV2/Rogiel__l2jserver2/data/templates/npc.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema version="1.0" targetNamespace="npc" xmlns:npc="npc"
	xmlns:actor="actor" xmlns:template="template" xmlns:xs="http://www.w3.org/2001/XMLSchema"
	elementFormDefault="qualified">
	<xs:import namespace="template" schemaLocation="template.xsd" />
	<xs:import namespace="actor" schemaLocation="actor.xsd" />

	<xs:complexType name="npcTemplate">
		<xs:complexContent>
			<xs:extension base="actor:actorTemplate">
				<xs:sequence>
					<xs:element name="info" type="npc:npcInformationMetadata"
						minOccurs="1" maxOccurs="1" />
					<xs:element name="ai" type="npc:aiMetadata" minOccurs="0"
						maxOccurs="1" />
					<xs:element name="teleporter" type="npc:teleporterMetadata"
						minOccurs="0" maxOccurs="1" />
					<xs:element name="talk" type="npc:talkMetadata"
						minOccurs="0" maxOccurs="1" />
					<xs:element name="droplist" minOccurs="0"
						maxOccurs="1">
						<xs:complexType>
							<xs:sequence>
								<xs:element name="item"
									type="npc:dropItemMetadata" minOccurs="0"
									maxOccurs="unbounded" />
							</xs:sequence>
						</xs:complexType>
					</xs:element>
					<xs:element name="skills" minOccurs="0"
						maxOccurs="1">
						<xs:complexType>
							<xs:sequence>
								<xs:element name="skill" minOccurs="1"
									maxOccurs="unbounded">
									<xs:complexType>
										<xs:attribute name="id" />
										<xs:attribute name="level" />
									</xs:complexType>
								</xs:element>
							</xs:sequence>
						</xs:complexType>
					</xs:element>
				</xs:sequence>
				<xs:attribute name="type" type="xs:string" />
				<xs:attribute name="controller" type="xs:string"></xs:attribute>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="npcInformationMetadata">
		<xs:sequence>
			<xs:element name="name" type="npc:npcNameMetadata"
				minOccurs="0" />
			<xs:element name="title" type="npc:npcTitleMetadata"
				minOccurs="0" />
			<xs:element name="level" type="xs:int" />
			<xs:element name="race" type="npc:npcRace" />
			<xs:element name="sex" type="actor:actorSex" minOccurs="0" />
			<xs:element name="stats" type="npc:npcStatsMetadata"
				minOccurs="0" />
			<xs:element name="experience" type="xs:long" />
			<xs:element name="sp" type="xs:int" />
			<xs:element name="item" type="npc:itemMetadata" minOccurs="0" />
			<xs:element name="collision" type="npc:collisionMetadata"
				minOccurs="0" />
		</xs:sequence>
		<xs:attribute name="attackable" type="xs:boolean" />
		<xs:attribute name="targetable" type="xs:boolean" />
		<xs:attribute name="aggressive" type="xs:boolean" />
	</xs:complexType>

	<xs:complexType name="npcNameMetadata">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="send" type="xs:boolean" />
				<xs:attribute name="display" type="xs:boolean" />
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>

	<xs:complexType name="npcTitleMetadata">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="send" type="xs:boolean" />
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>

	<xs:complexType name="npcStatsMetadata">
		<xs:sequence>
			<xs:element name="hp" type="npc:stat" minOccurs="0" />
			<xs:element name="mp" type="npc:stat" minOccurs="0" />
			<xs:element name="attack" type="npc:attackMetadata"
				minOccurs="0" />
			<xs:element name="defense" type="npc:defenseMetadata"
				minOccurs="0" />
			<xs:element name="move" type="npc:moveMetadata" minOccurs="0" />
			<xs:element name="base" type="npc:baseMetadata" minOccurs="0" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="stat">
		<xs:sequence />
		<xs:attribute name="max" type="xs:double" use="required" />
		<xs:attribute name="regen" type="xs:double" use="required" />
	</xs:complexType>

	<xs:complexType name="attackMetadata">
		<xs:sequence>
			<xs:element name="physical" type="npc:attackValueMetadata"
				minOccurs="0" />
			<xs:element name="magical" type="npc:attackValueMetadata"
				minOccurs="0" />
		</xs:sequence>
		<xs:attribute name="range" type="xs:int" use="required" />
		<xs:attribute name="evasion" type="xs:int" use="required" />
		<xs:attribute name="critical" type="xs:int" use="required" />
	</xs:complexType>

	<xs:complexType name="attackValueMetadata">
		<xs:sequence />
		<xs:attribute name="damage" type="xs:double" use="required" />
		<xs:attribute name="speed" type="xs:double" use="required" />
	</xs:complexType>

	<xs:complexType name="defenseMetadata">
		<xs:sequence>
			<xs:element name="physical" type="npc:defenseValueMetadata"
				minOccurs="0" />
			<xs:element name="magical" type="npc:defenseValueMetadata"
				minOccurs="0" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="defenseValueMetadata">
		<xs:sequence />
		<xs:attribute name="value" type="xs:double" use="required" />
	</xs:complexType>

	<xs:complexType name="moveMetadata">
		<xs:sequence />
		<xs:attribute name="run" type="xs:double" use="required" />
		<xs:attribute name="walk" type="xs:double" use="required" />
	</xs:complexType>

	<xs:complexType name="baseMetadata">
		<xs:sequence />
		<xs:attribute name="int" type="xs:int" use="required" />
		<xs:attribute name="str" type="xs:int" use="required" />
		<xs:attribute name="con" type="xs:int" use="required" />
		<xs:attribute name="men" type="xs:int" use="required" />
		<xs:attribute name="dex" type="xs:int" use="required" />
		<xs:attribute name="wit" type="xs:int" use="required" />
	</xs:complexType>

	<xs:complexType name="itemMetadata">
		<xs:sequence />
		<xs:attribute name="righthand" type="xs:int" />
		<xs:attribute name="lefthand" type="xs:int" />
	</xs:complexType>

	<xs:complexType name="collisionMetadata">
		<xs:sequence />
		<xs:attribute name="radius" type="xs:double" use="required" />
		<xs:attribute name="heigth" type="xs:double" use="required" />
	</xs:complexType>

	<xs:complexType name="aiMetadata">
		<xs:sequence />
		<xs:attribute name="script" type="xs:string" />
	</xs:complexType>

	<xs:complexType name="teleporterMetadata">
		<xs:sequence>
			<xs:element name="teleport" type="npc:teleporterTeleportMetadata"
				minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
		<xs:attribute name="default" type="xs:string" />
	</xs:complexType>

	<xs:complexType name="teleporterTeleportMetadata">
		<xs:sequence>
			<xs:element name="region" type="npc:teleportRegion"
				minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
		<xs:attribute name="id" type="xs:string" />
	</xs:complexType>

	<xs:complexType name="teleportRegion">
		<xs:sequence />
		<xs:attribute name="id" type="xs:string" />
		<xs:attribute name="price" type="xs:int" use="required" />
		<xs:attribute name="item" type="xs:int" />
	</xs:complexType>

	<xs:complexType name="talkMetadata">
		<xs:sequence>
			<xs:element name="chat" type="npc:chat" minOccurs="0"
				maxOccurs="unbounded" />
		</xs:sequence>
		<xs:attribute name="default" type="xs:string" />
	</xs:complexType>

	<xs:complexType name="chat">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="id" type="xs:string" />
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>

	<xs:complexType name="dropItemMetadata">
		<xs:sequence />
		<xs:attribute name="id" type="xs:int" />
		<xs:attribute name="min" type="xs:int" use="required" />
		<xs:attribute name="max" type="xs:int" use="required" />
		<xs:attribute name="category" type="npc:dropCategory" />
		<xs:attribute name="chance" type="xs:int" use="required" />
	</xs:complexType>

	<xs:simpleType name="npcRace">
		<xs:restriction base="xs:string">
			<xs:enumeration value="HUMAN" />
			<xs:enumeration value="ELVEN" />
			<xs:enumeration value="DARKELVEN" />
			<xs:enumeration value="ORC" />
			<xs:enumeration value="DWARVEN" />
			<xs:enumeration value="KAMAEL" />
			<xs:enumeration value="UNDEAD" />
			<xs:enumeration value="MAGIC_CREATURE" />
			<xs:enumeration value="BEAST" />
			<xs:enumeration value="ANIMAL" />
			<xs:enumeration value="PLANT" />
			<xs:enumeration value="HUMANOID" />
			<xs:enumeration value="SPIRIT" />
			<xs:enumeration value="ANGEL" />
			<xs:enumeration value="DEMON" />
			<xs:enumeration value="DRAGON" />
			<xs:enumeration value="GIANT" />
			<xs:enumeration value="BUG" />
			<xs:enumeration value="FAIRIE" />
			<xs:enumeration value="OTHER" />
			<xs:enumeration value="NON_LIVING" />
			<xs:enumeration value="SIEGE_WEAPON" />
			<xs:enumeration value="DEFENDING_ARMY" />
			<xs:enumeration value="MERCENARIE" />
			<xs:enumeration value="UNKNOWN" />
			<xs:enumeration value="NONE" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="dropCategory">
		<xs:restriction base="xs:string">
			<xs:enumeration value="DROP" />
			<xs:enumeration value="SPOIL" />
			<xs:enumeration value="UNK_1" />
			<xs:enumeration value="UNK_2" />
			<xs:enumeration value="UNK_3" />
			<xs:enumeration value="UNK_4" />
			<xs:enumeration value="UNK_5" />
			<xs:enumeration value="UNK_6" />
			<xs:enumeration value="UNK_7" />
			<xs:enumeration value="UNK_8" />
			<xs:enumeration value="UNK_9" />
			<xs:enumeration value="UNK_10" />
			<xs:enumeration value="UNK_11" />
			<xs:enumeration value="UNK_12" />
			<xs:enumeration value="UNK_13" />
			<xs:enumeration value="UNK_14" />
			<xs:enumeration value="UNK_15" />
			<xs:enumeration value="UNK_16" />
			<xs:enumeration value="UNK_17" />
			<xs:enumeration value="UNK_18" />
			<xs:enumeration value="UNK_19" />
			<xs:enumeration value="UNK_20" />
			<xs:enumeration value="UNK_21" />
			<xs:enumeration value="UNK_22" />
			<xs:enumeration value="UNK_23" />
			<xs:enumeration value="UNK_24" />
			<xs:enumeration value="UNK_25" />
			<xs:enumeration value="UNK_26" />
			<xs:enumeration value="UNK_27" />
			<xs:enumeration value="UNK_28" />
			<xs:enumeration value="UNK_29" />
			<xs:enumeration value="UNK_30" />
			<xs:enumeration value="UNK_31" />
			<xs:enumeration value="UNK_32" />
			<xs:enumeration value="UNK_33" />
			<xs:enumeration value="UNK_34" />
			<xs:enumeration value="UNK_35" />
			<xs:enumeration value="UNK_36" />
			<xs:enumeration value="UNK_100" />
			<xs:enumeration value="UNK_101" />
			<xs:enumeration value="UNK_102" />
			<xs:enumeration value="UNK_200" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="teleportRestriction">
		<xs:restriction base="xs:string">
			<xs:enumeration value="NOBLE" />
		</xs:restriction>
	</xs:simpleType>

	<xs:element name="npc" type="npc:npcTemplate"></xs:element>
</xs:schema>

=== BulkSecurityGeneratorProjectV2/Rogiel__l2jserver2/data/templates/npc/monster/18551-CrumaPhantom.xml
<?xml version="1.0" encoding="UTF-8"?>
<npc type="Monster" id="18551" xsi:schemaLocation="npc ../../npc.xsd"
    xsi:noNamespaceSchemaLocation="npc" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <info aggressive="false" targetable="true" attackable="false">
        <name display="true" send="false">Cruma Phantom</name>
        <title send="false">Event Monster</title>
        <level>50</level>
        <sex>MALE</sex>
        <stats>
            <hp regen="37.2348110463089" max="53155.2086342172"/>
            <mp regen="2.1" max="747.8"/>
            <attack critical="1" evasion="0" range="40">
                <physical speed="253.0" damage="491.12346"/>
                <magical speed="333.0" damage="335.37366"/>
            </attack>
            <defense>
                <physical value="320.3815"/>
                <magical value="351.66192"/>
            </defense>
            <move walk="27.0" run="150.0"/>
            <base wit="20" dex="30" men="20" con="43" str="40" int="21"/>
        </stats>
        <experience>0</experience>
        <sp>0</sp>
        <collision heigth="35.0" radius="20.0"/>
    </info>
</npc>

=== BulkSecurityGeneratorProjectV2/Rogiel__l2jserver2/data/templates/npc/raidboss/25420-OrfenSHandmaiden.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<npc xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" type="RaidBoss" id="25420" xsi:schemaLocation="npc ../../npc.xsd" xsi:noNamespaceSchemaLocation="npc">
    <info aggressive="false" targetable="true" attackable="false">
        <name display="true" send="false">Orfen's Handmaiden</name>
        <title send="false">Raid Boss</title>
        <level>48</level>
        <sex>FEMALE</sex>
        <stats>
            <hp regen="49.5883641293912" max="141171.403298766"/>
            <mp regen="2.1" max="692.4"/>
            <attack critical="8" evasion="0" range="40">
                <physical speed="253.0" damage="405.1994"/>
                <magical speed="333.0" damage="47.84373"/>
            </attack>
            <defense>
                <physical value="573.38409"/>
                <magical value="279.72"/>
            </defense>
            <move walk="60.0" run="190.0"/>
            <base wit="70" dex="73" men="80" con="57" str="60" int="76"/>
        </stats>
        <experience>2266583</experience>
        <sp>270998</sp>
        <collision heigth="72.0" radius="25.0"/>
    </info>
    <droplist>
        <item chance="38731" max="1" min="1" id="266"/>
        <item chance="73761" max="1" min="1" id="442"/>
        <item chance="117977" max="1" min="1" id="473"/>
        <item chance="93908" max="63" min="21" id="952"/>
        <item chance="389745" max="22" min="8" id="1988"/>
        <item chance="191045" max="72" min="24" id="1989"/>
        <item chance="730779" max="9" min="3" id="2120"/>
        <item chance="164340" max="6" min="2" id="4604"/>
        <item chance="131472" max="7" min="3" id="4605"/>
        <item chance="109560" max="9" min="3" id="4606"/>
        <item chance="840000" max="1" min="1" id="8176"/>
        <item chance="840000" max="3" min="1" id="9816"/>
    </droplist>
</npc>

=== BulkSecurityGeneratorProjectV2/Rogiel__l2jserver2/data/templates/npc/monster/22463-GluttonousKanabion.xml
<?xml version="1.0" encoding="UTF-8"?>
<npc
    controller="com.l2jserver.model.world.npc.controller.NotImplementedNPCController"
    id="22463" xsi:schemaLocation="npc ../../npc.xsd"
    xsi:noNamespaceSchemaLocation="npc" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <info aggressive="false" targetable="true" attackable="true">
        <name display="true" send="false">Gluttonous Kanabion</name>
        <title send="false">Void</title>
        <level>42</level>
        <sex>MALE</sex>
        <stats>
            <hp regen="4.5" max="966.57792"/>
            <mp regen="1.8" max="478.8"/>
            <attack critical="4" evasion="0" range="40">
                <physical speed="253.0" damage="176.36077"/>
                <magical speed="333.0" damage="120.43155"/>
            </attack>
            <defense>
                <physical value="156.55035"/>
                <magical value="114.55675"/>
            </defense>
            <move walk="18.0" run="150.0"/>
            <base wit="20" dex="30" men="20" con="43" str="40" int="21"/>
        </stats>
        <experience>3243</experience>
        <sp>189</sp>
        <item lefthand="0" righthand="5130"/>
        <collision heigth="42.0" radius="26.0"/>
    </info>
    <droplist>
        <item chance="25700" max="1" min="1" id="956"/>
    </droplist>
</npc>

=== BulkSecurityGeneratorProjectV2/Rogiel__l2jserver2/l2jserver2-gameserver/data/template/npc/monster/22363-BodyDestroyer.xml
<?xml version="1.0" encoding="UTF-8"?>
<template:npc
    controller="com.l2jserver.model.world.npc.controller.MonsterController"
    id="22363" xsi:schemaLocation="http://schemas.l2jserver2.com/npc ../../npc.xsd"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:template="http://schemas.l2jserver2.com/npc">
    <info aggressive="true" targetable="true" attackable="true">
        <name display="true" send="false">Body Destroyer</name>
        <level>83</level>
        <race>UNDEAD</race>
        <sex>MALE</sex>
        <stats>
            <hp regen="190.897045965523" max="56202.8420013809"/>
            <mp regen="3.0" max="1777.4"/>
            <attack critical="1" evasion="0" range="40">
                <physical speed="253.0" damage="9440.59974"/>
                <magical speed="333.0" damage="6521.6675"/>
            </attack>
            <defense>
                <physical value="585.59197"/>
                <magical value="642.76618"/>
            </defense>
            <move walk="51.0" run="160.0"/>
            <base wit="20" dex="30" men="20" con="43" str="40" int="21"/>
        </stats>
        <experience>314158</experience>
        <sp>33124</sp>
        <collision heigth="31.5" radius="14.0"/>
    </info>
    <droplist>
        <item chance="700000" category="DROP" max="68413" min="34159" id="57"/>
        <item chance="200000" category="UNK_101" max="1" min="1" id="9685"/>
        <item chance="13130" category="UNK_1" max="1" min="1" id="5545"/>
        <item chance="14422" category="UNK_1" max="1" min="1" id="5546"/>
        <item chance="13130" category="UNK_1" max="1" min="1" id="5529"/>
        <item chance="99749" category="UNK_2" max="9" min="3" id="1879"/>
        <item chance="299247" category="UNK_2" max="1" min="1" id="1885"/>
        <item chance="28164" category="UNK_2" max="1" min="1" id="9628"/>
        <item chance="18900" category="UNK_2" max="1" min="1" id="9630"/>
        <item chance="15613" category="UNK_2" max="1" min="1" id="9629"/>
        <item chance="28727" category="UNK_200" max="1" min="1" id="9551"/>
        <item chance="6367" category="UNK_2" max="1" min="1" id="6861"/>
        <item chance="144" category="UNK_2" max="1" min="1" id="959"/>
        <item chance="46" category="UNK_1" max="1" min="1" id="81"/>
        <item chance="46" category="UNK_1" max="1" min="1" id="151"/>
        <item chance="46" category="UNK_1" max="1" min="1" id="2500"/>
        <item chance="946016" category="SPOIL" max="1" min="1" id="6706"/>
        <item chance="813293" category="SPOIL" max="1" min="1" id="6705"/>
        <item chance="58317" category="SPOIL" max="1" min="1" id="6901"/>
    </droplist>
    <skills>
        <skill level="1" id="4408"/>
        <skill level="1" id="4409"/>
        <skill level="11" id="4410"/>
        <skill level="11" id="4411"/>
        <skill level="11" id="4412"/>
        <skill level="11" id="4413"/>
        <skill level="2" id="4414"/>
        <skill level="5" id="4415"/>
        <skill level="1" id="4416"/>
        <skill level="1" id="5256"/>
        <skill level="1" id="5257"/>
        <skill level="5" id="5334"/>
        <skill level="1" id="5467"/>
    </skills>
</template:npc>

=== BulkSecurityGeneratorProjectV2/Rogiel__l2jserver2/l2jserver2-gameserver/data/templates/npc/monster/21062-MessengerAngel.xml
<?xml version="1.0" encoding="UTF-8"?>
<npc
    controller="com.l2jserver.model.world.npc.controller.MonsterController"
    id="21062" xsi:schemaLocation="npc ../../npc.xsd"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="npc">
    <info aggressive="true" targetable="true" attackable="true">
        <name display="true" send="false">Messenger Angel</name>
        <level>70</level>
        <race>ANGEL</race>
        <sex>MALE</sex>
        <stats>
            <hp regen="7.5" max="2444.46819"/>
            <mp regen="2.7" max="1345.8"/>
            <attack critical="1" evasion="0" range="40">
                <physical speed="253.0" damage="688.86373"/>
                <magical speed="333.0" damage="470.40463"/>
            </attack>
            <defense>
                <physical value="295.91597"/>
                <magical value="197.0242"/>
            </defense>
            <move walk="30.0" run="174.0"/>
            <base wit="20" dex="30" men="20" con="43" str="40" int="21"/>
        </stats>
        <experience>0</experience>
        <sp>0</sp>
        <item lefthand="0" righthand="148"/>
        <collision heigth="36.5" radius="13.5"/>
    </info>
    <skills>
        <skill level="7" id="4033"/>
        <skill level="7" id="4073"/>
        <skill level="1" id="4085"/>
        <skill level="1" id="4086"/>
        <skill level="1" id="4092"/>
        <skill level="12" id="4408"/>
        <skill level="1" id="4409"/>
        <skill level="13" id="4410"/>
        <skill level="13" id="4411"/>
        <skill level="11" id="4412"/>
        <skill level="9" id="4413"/>
        <skill level="2" id="4414"/>
        <skill level="5" id="4415"/>
        <skill level="8" id="4416"/>
    </skills>
</npc>

=== BulkSecurityGeneratorProjectV2/Rogiel__l2jserver2/l2jserver2-gameserver/data/templates/npc/raidboss/25544-Tully.xml
<?xml version="1.0" encoding="UTF-8"?>
<npc
    controller="com.l2jserver.model.world.npc.controller.NotImplementedNPCController"
    id="25544" xsi:schemaLocation="npc ../../npc.xsd"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="npc">
    <info aggressive="false" targetable="true" attackable="true">
        <name display="true" send="false">Tully</name>
        <title send="false">Steel Citadel</title>
        <level>83</level>
        <race>HUMANOID</race>
        <sex>MALE</sex>
        <stats>
            <hp regen="171.837730607924" max="1697736.13723745"/>
            <mp regen="3.0" max="1881.8"/>
            <attack critical="4" evasion="0" range="40">
                <physical speed="253.0" damage="5285.98483"/>
                <magical speed="333.0" damage="3672.60127"/>
            </attack>
            <defense>
                <physical value="743.99459"/>
                <magical value="359.61279"/>
            </defense>
            <move walk="60.0" run="180.0"/>
            <base wit="20" dex="30" men="80" con="43" str="40" int="21"/>
        </stats>
        <experience>2522625</experience>
        <sp>1749150</sp>
        <collision heigth="32.5" radius="19.0"/>
    </info>
    <droplist>
        <item chance="46044" category="UNK_2" max="1" min="1" id="6680"/>
        <item chance="740368" category="UNK_2" max="36" min="12" id="6707"/>
        <item chance="11182" category="UNK_1" max="1" min="1" id="7575"/>
        <item chance="217808" category="UNK_1" max="36" min="12" id="7579"/>
    </droplist>
    <skills>
        <skill level="1" id="4045"/>
        <skill level="10" id="4168"/>
        <skill level="10" id="4187"/>
        <skill level="1" id="4408"/>
        <skill level="1" id="4409"/>
        <skill level="11" id="4410"/>
        <skill level="11" id="4411"/>
        <skill level="11" id="4412"/>
        <skill level="11" id="4413"/>
        <skill level="2" id="4414"/>
        <skill level="1" id="4415"/>
        <skill level="6" id="4416"/>
        <skill level="1" id="4494"/>
        <skill level="1" id="5467"/>
        <skill level="1" id="5477"/>
        <skill level="1" id="5479"/>
    </skills>
</npc>

=== BulkSecurityGeneratorProjectV2/Rogiel__l2jserver2/data/templates/npc/monster/27193-GoblinServant.xml
<?xml version="1.0" encoding="UTF-8"?>
<npc
    controller="com.l2jserver.model.world.npc.controller.MonsterController"
    id="27193" xsi:schemaLocation="npc ../../npc.xsd"
    xsi:noNamespaceSchemaLocation="npc" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <info aggressive="true" targetable="true" attackable="true">
        <name display="true" send="false">Goblin Servant</name>
        <title send="false">Quest Monster</title>
        <level>12</level>
        <sex>MALE</sex>
        <stats>
            <hp regen="2.5" max="199.62322"/>
            <mp regen="1.2" max="124.48"/>
            <attack critical="4" evasion="0" range="40">
                <physical speed="253.0" damage="22.99606"/>
                <magical speed="333.0" damage="15.70333"/>
            </attack>
            <defense>
                <physical value="66.32989"/>
                <magical value="48.53733"/>
            </defense>
            <move walk="40.0" run="120.0"/>
            <base wit="20" dex="30" men="20" con="43" str="40" int="21"/>
        </stats>
        <experience>0</experience>
        <sp>0</sp>
        <collision heigth="16.5" radius="10.0"/>
    </info>
</npc>

=== BulkSecurityGeneratorProjectV2/Rogiel__l2jserver2/data/templates/npc/pet/14615-Soulless.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<npc xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" type="Pet" id="14615" xsi:schemaLocation="npc ../../npc.xsd" xsi:noNamespaceSchemaLocation="npc">
    <info aggressive="false" targetable="true" attackable="false">
        <name display="true" send="false">Soulless</name>
        <level>84</level>
        <sex>MALE</sex>
        <stats>
            <hp regen="8.5" max="3032.639435"/>
            <mp regen="3.0" max="1829.3"/>
            <attack critical="4" evasion="0" range="40">
                <physical speed="253.0" damage="975.16116"/>
                <magical speed="333.0" damage="665.90866"/>
            </attack>
            <defense>
                <physical value="359.87013"/>
                <magical value="263.33734"/>
            </defense>
            <move walk="48.0" run="180.0"/>
            <base wit="20" dex="30" men="25" con="43" str="40" int="21"/>
        </stats>
        <experience>0</experience>
        <sp>0</sp>
        <collision heigth="28.0" radius="7.0"/>
    </info>
</npc>
