=== BulkSecurityGeneratorProjectV2/Rogiel__l2jserver2/data/templates/npc.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema version="1.0" targetNamespace="npc" xmlns:npc="npc"
	xmlns:actor="actor" xmlns:template="template" xmlns:xs="http://www.w3.org/2001/XMLSchema"
	elementFormDefault="qualified">
	<xs:import namespace="template" schemaLocation="template.xsd" />
	<xs:import namespace="actor" schemaLocation="actor.xsd" />

	<xs:complexType name="npcTemplate">
		<xs:complexContent>
			<xs:extension base="actor:actorTemplate">
				<xs:sequence>
					<xs:element name="info" type="npc:npcInformationMetadata"
						minOccurs="1" maxOccurs="1" />
					<xs:element name="ai" type="npc:aiMetadata" minOccurs="0"
						maxOccurs="1" />
					<xs:element name="teleporter" type="npc:teleporterMetadata"
						minOccurs="0" maxOccurs="1" />
					<xs:element name="talk" type="npc:talkMetadata"
						minOccurs="0" maxOccurs="1" />
					<xs:element name="droplist" minOccurs="0"
						maxOccurs="1">
						<xs:complexType>
							<xs:sequence>
								<xs:element name="item"
									type="npc:dropItemMetadata" minOccurs="0"
									maxOccurs="unbounded" />
							</xs:sequence>
						</xs:complexType>
					</xs:element>
					<xs:element name="skills" minOccurs="0"
						maxOccurs="1">
						<xs:complexType>
							<xs:sequence>
								<xs:element name="skill" minOccurs="1"
									maxOccurs="unbounded">
									<xs:complexType>
										<xs:attribute name="id" />
										<xs:attribute name="level" />
									</xs:complexType>
								</xs:element>
							</xs:sequence>
						</xs:complexType>
					</xs:element>
				</xs:sequence>
				<xs:attribute name="type" type="xs:string" />
				<xs:attribute name="controller" type="xs:string"></xs:attribute>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="npcInformationMetadata">
		<xs:sequence>
			<xs:element name="name" type="npc:npcNameMetadata"
				minOccurs="0" />
			<xs:element name="title" type="npc:npcTitleMetadata"
				minOccurs="0" />
			<xs:element name="level" type="xs:int" />
			<xs:element name="race" type="npc:npcRace" />
			<xs:element name="sex" type="actor:actorSex" minOccurs="0" />
			<xs:element name="stats" type="npc:npcStatsMetadata"
				minOccurs="0" />
			<xs:element name="experience" type="xs:long" />
			<xs:element name="sp" type="xs:int" />
			<xs:element name="item" type="npc:itemMetadata" minOccurs="0" />
			<xs:element name="collision" type="npc:collisionMetadata"
				minOccurs="0" />
		</xs:sequence>
		<xs:attribute name="attackable" type="xs:boolean" />
		<xs:attribute name="targetable" type="xs:boolean" />
		<xs:attribute name="aggressive" type="xs:boolean" />
	</xs:complexType>

	<xs:complexType name="npcNameMetadata">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="send" type="xs:boolean" />
				<xs:attribute name="display" type="xs:boolean" />
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>

	<xs:complexType name="npcTitleMetadata">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="send" type="xs:boolean" />
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>

	<xs:complexType name="npcStatsMetadata">
		<xs:sequence>
			<xs:element name="hp" type="npc:stat" minOccurs="0" />
			<xs:element name="mp" type="npc:stat" minOccurs="0" />
			<xs:element name="attack" type="npc:attackMetadata"
				minOccurs="0" />
			<xs:element name="defense" type="npc:defenseMetadata"
				minOccurs="0" />
			<xs:element name="move" type="npc:moveMetadata" minOccurs="0" />
			<xs:element name="base" type="npc:baseMetadata" minOccurs="0" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="stat">
		<xs:sequence />
		<xs:attribute name="max" type="xs:double" use="required" />
		<xs:attribute name="regen" type="xs:double" use="required" />
	</xs:complexType>

	<xs:complexType name="attackMetadata">
		<xs:sequence>
			<xs:element name="physical" type="npc:attackValueMetadata"
				minOccurs="0" />
			<xs:element name="magical" type="npc:attackValueMetadata"
				minOccurs="0" />
		</xs:sequence>
		<xs:attribute name="range" type="xs:int" use="required" />
		<xs:attribute name="evasion" type="xs:int" use="required" />
		<xs:attribute name="critical" type="xs:int" use="required" />
	</xs:complexType>

	<xs:complexType name="attackValueMetadata">
		<xs:sequence />
		<xs:attribute name="damage" type="xs:double" use="required" />
		<xs:attribute name="speed" type="xs:double" use="required" />
	</xs:complexType>

	<xs:complexType name="defenseMetadata">
		<xs:sequence>
			<xs:element name="physical" type="npc:defenseValueMetadata"
				minOccurs="0" />
			<xs:element name="magical" type="npc:defenseValueMetadata"
				minOccurs="0" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="defenseValueMetadata">
		<xs:sequence />
		<xs:attribute name="value" type="xs:double" use="required" />
	</xs:complexType>

	<xs:complexType name="moveMetadata">
		<xs:sequence />
		<xs:attribute name="run" type="xs:double" use="required" />
		<xs:attribute name="walk" type="xs:double" use="required" />
	</xs:complexType>

	<xs:complexType name="baseMetadata">
		<xs:sequence />
		<xs:attribute name="int" type="xs:int" use="required" />
		<xs:attribute name="str" type="xs:int" use="required" />
		<xs:attribute name="con" type="xs:int" use="required" />
		<xs:attribute name="men" type="xs:int" use="required" />
		<xs:attribute name="dex" type="xs:int" use="required" />
		<xs:attribute name="wit" type="xs:int" use="required" />
	</xs:complexType>

	<xs:complexType name="itemMetadata">
		<xs:sequence />
		<xs:attribute name="righthand" type="xs:int" />
		<xs:attribute name="lefthand" type="xs:int" />
	</xs:complexType>

	<xs:complexType name="collisionMetadata">
		<xs:sequence />
		<xs:attribute name="radius" type="xs:double" use="required" />
		<xs:attribute name="heigth" type="xs:double" use="required" />
	</xs:complexType>

	<xs:complexType name="aiMetadata">
		<xs:sequence />
		<xs:attribute name="script" type="xs:string" />
	</xs:complexType>

	<xs:complexType name="teleporterMetadata">
		<xs:sequence>
			<xs:element name="teleport" type="npc:teleporterTeleportMetadata"
				minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
		<xs:attribute name="default" type="xs:string" />
	</xs:complexType>

	<xs:complexType name="teleporterTeleportMetadata">
		<xs:sequence>
			<xs:element name="region" type="npc:teleportRegion"
				minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
		<xs:attribute name="id" type="xs:string" />
	</xs:complexType>

	<xs:complexType name="teleportRegion">
		<xs:sequence />
		<xs:attribute name="id" type="xs:string" />
		<xs:attribute name="price" type="xs:int" use="required" />
		<xs:attribute name="item" type="xs:int" />
	</xs:complexType>

	<xs:complexType name="talkMetadata">
		<xs:sequence>
			<xs:element name="chat" type="npc:chat" minOccurs="0"
				maxOccurs="unbounded" />
		</xs:sequence>
		<xs:attribute name="default" type="xs:string" />
	</xs:complexType>

	<xs:complexType name="chat">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="id" type="xs:string" />
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>

	<xs:complexType name="dropItemMetadata">
		<xs:sequence />
		<xs:attribute name="id" type="xs:int" />
		<xs:attribute name="min" type="xs:int" use="required" />
		<xs:attribute name="max" type="xs:int" use="required" />
		<xs:attribute name="category" type="npc:dropCategory" />
		<xs:attribute name="chance" type="xs:int" use="required" />
	</xs:complexType>

	<xs:simpleType name="npcRace">
		<xs:restriction base="xs:string">
			<xs:enumeration value="HUMAN" />
			<xs:enumeration value="ELVEN" />
			<xs:enumeration value="DARKELVEN" />
			<xs:enumeration value="ORC" />
			<xs:enumeration value="DWARVEN" />
			<xs:enumeration value="KAMAEL" />
			<xs:enumeration value="UNDEAD" />
			<xs:enumeration value="MAGIC_CREATURE" />
			<xs:enumeration value="BEAST" />
			<xs:enumeration value="ANIMAL" />
			<xs:enumeration value="PLANT" />
			<xs:enumeration value="HUMANOID" />
			<xs:enumeration value="SPIRIT" />
			<xs:enumeration value="ANGEL" />
			<xs:enumeration value="DEMON" />
			<xs:enumeration value="DRAGON" />
			<xs:enumeration value="GIANT" />
			<xs:enumeration value="BUG" />
			<xs:enumeration value="FAIRIE" />
			<xs:enumeration value="OTHER" />
			<xs:enumeration value="NON_LIVING" />
			<xs:enumeration value="SIEGE_WEAPON" />
			<xs:enumeration value="DEFENDING_ARMY" />
			<xs:enumeration value="MERCENARIE" />
			<xs:enumeration value="UNKNOWN" />
			<xs:enumeration value="NONE" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="dropCategory">
		<xs:restriction base="xs:string">
			<xs:enumeration value="DROP" />
			<xs:enumeration value="SPOIL" />
			<xs:enumeration value="UNK_1" />
			<xs:enumeration value="UNK_2" />
			<xs:enumeration value="UNK_3" />
			<xs:enumeration value="UNK_4" />
			<xs:enumeration value="UNK_5" />
			<xs:enumeration value="UNK_6" />
			<xs:enumeration value="UNK_7" />
			<xs:enumeration value="UNK_8" />
			<xs:enumeration value="UNK_9" />
			<xs:enumeration value="UNK_10" />
			<xs:enumeration value="UNK_11" />
			<xs:enumeration value="UNK_12" />
			<xs:enumeration value="UNK_13" />
			<xs:enumeration value="UNK_14" />
			<xs:enumeration value="UNK_15" />
			<xs:enumeration value="UNK_16" />
			<xs:enumeration value="UNK_17" />
			<xs:enumeration value="UNK_18" />
			<xs:enumeration value="UNK_19" />
			<xs:enumeration value="UNK_20" />
			<xs:enumeration value="UNK_21" />
			<xs:enumeration value="UNK_22" />
			<xs:enumeration value="UNK_23" />
			<xs:enumeration value="UNK_24" />
			<xs:enumeration value="UNK_25" />
			<xs:enumeration value="UNK_26" />
			<xs:enumeration value="UNK_27" />
			<xs:enumeration value="UNK_28" />
			<xs:enumeration value="UNK_29" />
			<xs:enumeration value="UNK_30" />
			<xs:enumeration value="UNK_31" />
			<xs:enumeration value="UNK_32" />
			<xs:enumeration value="UNK_33" />
			<xs:enumeration value="UNK_34" />
			<xs:enumeration value="UNK_35" />
			<xs:enumeration value="UNK_36" />
			<xs:enumeration value="UNK_100" />
			<xs:enumeration value="UNK_101" />
			<xs:enumeration value="UNK_102" />
			<xs:enumeration value="UNK_200" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="teleportRestriction">
		<xs:restriction base="xs:string">
			<xs:enumeration value="NOBLE" />
		</xs:restriction>
	</xs:simpleType>

	<xs:element name="npc" type="npc:npcTemplate"></xs:element>
</xs:schema>

=== BulkSecurityGeneratorProjectV2/Rogiel__l2jserver2/l2jserver2-gameserver/data/template/npc/monster/18070-ApostateSOffering.xml
<?xml version="1.0" encoding="UTF-8"?>
<template:npc
    controller="com.l2jserver.model.world.npc.controller.impl.NotImplementedNPCController"
    id="18070" xsi:schemaLocation="http://schemas.l2jserver2.com/npc ../../npc.xsd"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:template="http://schemas.l2jserver2.com/npc">
    <info aggressive="false" targetable="true" attackable="true">
        <name display="true" send="false">Apostate's Offering</name>
        <level>43</level>
        <race>HUMANOID</race>
        <sex>MALE</sex>
        <stats>
            <hp regen="5.5" max="1094.28943"/>
            <mp regen="2.1" max="557.4"/>
            <attack critical="8" evasion="0" range="40">
                <physical speed="253.0" damage="183.79228"/>
                <magical speed="333.0" damage="143.43577"/>
            </attack>
            <defense>
                <physical value="143.76404"/>
                <magical value="102.45795"/>
            </defense>
            <move walk="45.0" run="30.0"/>
            <base wit="20" dex="30" men="20" con="43" str="40" int="21"/>
        </stats>
        <experience>2751</experience>
        <sp>186</sp>
        <item leftHand="0" rightHand="223"/>
        <collision heigth="22.0" radius="12.0"/>
    </info>
    <droplist>
        <item chance="700000" category="DROP" max="611" min="305" id="57"/>
    </droplist>
    <skills>
        <skill level="1" id="4408"/>
        <skill level="1" id="4409"/>
        <skill level="11" id="4410"/>
        <skill level="11" id="4411"/>
        <skill level="11" id="4412"/>
        <skill level="11" id="4413"/>
        <skill level="3" id="4414"/>
        <skill level="7" id="4415"/>
        <skill level="6" id="4416"/>
        <skill level="2" id="4438"/>
        <skill level="2" id="4439"/>
        <skill level="2" id="4444"/>
        <skill level="2" id="4445"/>
    </skills>
</template:npc>

=== BulkSecurityGeneratorProjectV2/Rogiel__l2jserver2/data/templates/npc/riftinvader/21715-PurgatoryInvaderDisciples.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<npc xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" type="RiftInvader" id="21715" xsi:schemaLocation="npc ../../npc.xsd" xsi:noNamespaceSchemaLocation="npc">
    <info aggressive="false" targetable="true" attackable="false">
        <name display="true" send="false">Purgatory Invader Disciples</name>
        <level>53</level>
        <sex>MALE</sex>
        <stats>
            <hp regen="6.5" max="1570.8463"/>
            <mp regen="2.4" max="832.4"/>
            <attack critical="8" evasion="0" range="40">
                <physical speed="253.0" damage="353.71092"/>
                <magical speed="333.0" damage="241.5387"/>
            </attack>
            <defense>
                <physical value="214.18326"/>
                <magical value="142.60563"/>
            </defense>
            <move walk="80.0" run="165.0"/>
            <base wit="20" dex="30" men="20" con="43" str="40" int="21"/>
        </stats>
        <experience>9873</experience>
        <sp>776</sp>
        <item lefthand="946" righthand="946"/>
        <collision heigth="28.5" radius="11.0"/>
    </info>
    <droplist>
        <item chance="700000" max="2660" min="1309" id="57"/>
        <item chance="74" max="1" min="1" id="442"/>
        <item chance="118" max="1" min="1" id="473"/>
        <item chance="162835" max="1" min="1" id="1867"/>
        <item chance="162835" max="1" min="1" id="1872"/>
        <item chance="27139" max="1" min="1" id="1882"/>
        <item chance="4285" max="1" min="1" id="1894"/>
        <item chance="50463" max="1" min="1" id="1987"/>
        <item chance="5867" max="1" min="1" id="1988"/>
        <item chance="9202" max="1" min="1" id="1989"/>
        <item chance="2036" max="1" min="1" id="4042"/>
        <item chance="545813" max="1" min="1" id="4126"/>
        <item chance="81871" max="1" min="1" id="4127"/>
        <item chance="3023" max="1" min="1" id="4127"/>
        <item chance="2827" max="1" min="1" id="8726"/>
        <item chance="707" max="1" min="1" id="8736"/>
        <item chance="71" max="1" min="1" id="8746"/>
        <item chance="14" max="1" min="1" id="8756"/>
    </droplist>
</npc>

=== BulkSecurityGeneratorProjectV2/Rogiel__l2jserver2/data/templates/npc/monster/20134-CaveMaiden.xml
<?xml version="1.0" encoding="UTF-8"?>
<npc type="Monster" id="20134" xsi:schemaLocation="npc ../../npc.xsd"
    xsi:noNamespaceSchemaLocation="npc" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <info aggressive="true" targetable="true" attackable="false">
        <name display="true" send="false">Cave Maiden</name>
        <level>59</level>
        <sex>FEMALE</sex>
        <stats>
            <hp regen="6.5" max="1880.92519"/>
            <mp regen="2.4" max="1007.0"/>
            <attack critical="4" evasion="0" range="40">
                <physical speed="253.0" damage="461.94387"/>
                <magical speed="333.0" damage="315.44778"/>
            </attack>
            <defense>
                <physical value="242.81593"/>
                <magical value="161.66959"/>
            </defense>
            <move walk="70.0" run="174.0"/>
            <base wit="20" dex="30" men="20" con="43" str="40" int="21"/>
        </stats>
        <experience>6135</experience>
        <sp>524</sp>
        <item lefthand="0" righthand="68"/>
        <collision heigth="65.0" radius="25.0"/>
    </info>
    <droplist>
        <item chance="700000" max="1673" min="821" id="57"/>
        <item chance="233" max="1" min="1" id="356"/>
        <item chance="10" max="1" min="1" id="357"/>
        <item chance="15" max="1" min="1" id="383"/>
        <item chance="832" max="1" min="1" id="947"/>
        <item chance="20" max="1" min="1" id="947"/>
        <item chance="34121" max="1" min="1" id="1866"/>
        <item chance="693087" max="5" min="1" id="1871"/>
        <item chance="51182" max="1" min="1" id="1871"/>
        <item chance="4265" max="1" min="1" id="1885"/>
        <item chance="10" max="1" min="1" id="2376"/>
        <item chance="15" max="1" min="1" id="2379"/>
        <item chance="445" max="1" min="1" id="4041"/>
        <item chance="1390" max="1" min="1" id="4056"/>
        <item chance="2148" max="1" min="1" id="4057"/>
        <item chance="1390" max="1" min="1" id="4064"/>
        <item chance="2148" max="1" min="1" id="4065"/>
        <item chance="39" max="1" min="1" id="4192"/>
        <item chance="637" max="1" min="1" id="4993"/>
        <item chance="2047" max="1" min="1" id="5220"/>
        <item chance="853" max="1" min="1" id="8728"/>
        <item chance="213" max="1" min="1" id="8738"/>
        <item chance="21" max="1" min="1" id="8748"/>
        <item chance="5" max="1" min="1" id="8758"/>
    </droplist>
</npc>

=== BulkSecurityGeneratorProjectV2/Rogiel__l2jserver2/data/templates/npc/monster/21414-AssassinOfEmpire.xml
<?xml version="1.0" encoding="UTF-8"?>
<npc
    controller="com.l2jserver.model.world.npc.controller.MonsterController"
    id="21414" xsi:schemaLocation="npc ../../npc.xsd"
    xsi:noNamespaceSchemaLocation="npc" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <info aggressive="false" targetable="true" attackable="true">
        <name display="true" send="false">Assassin of Empire</name>
        <level>78</level>
        <race>UNDEAD</race>
        <sex>MALE</sex>
        <stats>
            <hp regen="8.721" max="2975.2369188"/>
            <mp regen="3.0804" max="1742.976"/>
            <attack critical="8" evasion="0" range="40">
                <physical speed="253.0" damage="938.20801"/>
                <magical speed="333.0" damage="656.66638"/>
            </attack>
            <defense>
                <physical value="354.81835"/>
                <magical value="239.18092"/>
            </defense>
            <move walk="80.0" run="175.0"/>
            <base wit="20" dex="30" men="20" con="43" str="40" int="21"/>
        </stats>
        <experience>36181</experience>
        <sp>4108</sp>
        <item lefthand="945" righthand="946"/>
        <collision heigth="28.5" radius="11.0"/>
    </info>
    <droplist>
        <item chance="700000" category="DROP" max="10446" min="5101" id="57"/>
        <item chance="153" category="UNK_2" max="1" min="1" id="960"/>
        <item chance="239255" category="UNK_2" max="60" min="20" id="1344"/>
        <item chance="63801" category="UNK_2" max="6" min="2" id="1866"/>
        <item chance="127602" category="UNK_2" max="3" min="1" id="1871"/>
        <item chance="414708" category="SPOIL" max="1" min="1" id="1877"/>
        <item chance="15312" category="UNK_2" max="1" min="1" id="1877"/>
        <item chance="207354" category="SPOIL" max="1" min="1" id="4040"/>
        <item chance="7656" category="UNK_2" max="1" min="1" id="4040"/>
        <item chance="3329" category="UNK_2" max="1" min="1" id="4041"/>
        <item chance="1313" category="UNK_1" max="1" min="1" id="5533"/>
        <item chance="1311" category="UNK_1" max="1" min="1" id="5544"/>
        <item chance="151985" category="SPOIL" max="1" min="1" id="6344"/>
        <item chance="1313" category="UNK_1" max="1" min="1" id="8342"/>
        <item chance="1312" category="UNK_1" max="1" min="1" id="8349"/>
        <item chance="3190" category="UNK_200" max="1" min="1" id="8732"/>
        <item chance="797" category="UNK_200" max="1" min="1" id="8742"/>
        <item chance="80" category="UNK_200" max="1" min="1" id="8752"/>
        <item chance="85" category="UNK_1" max="1" min="1" id="11966"/>
        <item chance="85" category="UNK_1" max="1" min="1" id="11969"/>
        <item chance="85" category="UNK_1" max="1" min="1" id="11970"/>
        <item chance="85" category="UNK_1" max="1" min="1" id="11974"/>
    </droplist>
    <skills>
        <skill level="1" id="4274"/>
        <skill level="13" id="4408"/>
        <skill level="1" id="4409"/>
        <skill level="13" id="4410"/>
        <skill level="13" id="4411"/>
        <skill level="9" id="4412"/>
        <skill level="9" id="4413"/>
        <skill level="2" id="4414"/>
        <skill level="7" id="4415"/>
        <skill level="1" id="4416"/>
        <skill level="9" id="4561"/>
        <skill level="9" id="4603"/>
        <skill level="9" id="4613"/>
        <skill level="7" id="4789"/>
    </skills>
</npc>

=== BulkSecurityGeneratorProjectV2/Rogiel__l2jserver2/l2jserver2-gameserver/data/template/npc/monster/18792-DefeatedTroopsJavelinThrower.xml
<?xml version="1.0" encoding="UTF-8"?>
<template:npc
    controller="com.l2jserver.model.world.npc.controller.impl.MonsterController"
    id="18792" xsi:schemaLocation="http://schemas.l2jserver2.com/npc ../../npc.xsd"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:template="http://schemas.l2jserver2.com/npc">
    <info aggressive="false" targetable="true" attackable="true">
        <name display="true" send="false">Defeated Troops Javelin Thrower</name>
        <level>80</level>
        <race>DRAGON</race>
        <sex>MALE</sex>
        <stats>
            <hp regen="195.86371266283" max="56659.3136360673"/>
            <mp regen="3.0" max="1674.8"/>
            <attack critical="8" evasion="0" range="1100">
                <physical speed="253.0" damage="9218.40693"/>
                <magical speed="333.0" damage="6294.97689"/>
            </attack>
            <defense>
                <physical value="546.2"/>
                <magical value="599.52818"/>
            </defense>
            <move walk="89.0" run="220.0"/>
            <base wit="20" dex="30" men="20" con="43" str="40" int="21"/>
        </stats>
        <experience>0</experience>
        <sp>0</sp>
        <item lefthand="0" righthand="13843"/>
        <collision heigth="46.5" radius="25.0"/>
    </info>
    <skills>
        <skill level="9" id="4408"/>
        <skill level="1" id="4409"/>
        <skill level="8" id="4410"/>
        <skill level="8" id="4411"/>
        <skill level="7" id="4412"/>
        <skill level="8" id="4413"/>
        <skill level="2" id="4414"/>
        <skill level="9" id="4415"/>
        <skill level="10" id="4416"/>
        <skill level="5" id="4441"/>
        <skill level="1" id="5462"/>
        <skill level="1" id="5837"/>
        <skill level="1" id="5838"/>
    </skills>
</template:npc>

=== BulkSecurityGeneratorProjectV2/Rogiel__l2jserver2/data/templates/npc/13224-Trap.xml
<?xml version="1.0" encoding="UTF-8"?>
<npc
    controller="com.l2jserver.model.world.npc.controller.BaseNPCController"
    id="13224" xsi:schemaLocation="npc ../npc.xsd"
    xsi:noNamespaceSchemaLocation="npc" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <info aggressive="false" targetable="true" attackable="true">
        <name display="true" send="false">Trap</name>
        <level>76</level>
        <race>OTHER</race>
        <stats>
            <hp regen="8.5" max="2758.05923328"/>
            <mp regen="3.0" max="1540.8"/>
            <attack critical="4" evasion="0" range="40">
                <physical speed="253.0" damage="824.42207"/>
                <magical speed="333.0" damage="562.9734"/>
            </attack>
            <defense>
                <physical value="323.78455"/>
                <magical value="236.93149"/>
            </defense>
            <move walk="50.0" run="1.0"/>
            <base wit="20" dex="30" men="20" con="43" str="40" int="21"/>
        </stats>
        <experience>0</experience>
        <sp>0</sp>
        <collision heigth="10.0" radius="5.0"/>
    </info>
    <skills>
        <skill level="1" id="4390"/>
        <skill level="1" id="4408"/>
        <skill level="1" id="4409"/>
        <skill level="11" id="4410"/>
        <skill level="11" id="4411"/>
        <skill level="11" id="4412"/>
        <skill level="11" id="4413"/>
        <skill level="2" id="4414"/>
        <skill level="1" id="4415"/>
        <skill level="19" id="4416"/>
        <skill level="7" id="5269"/>
    </skills>
</npc>
